# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#
# Gitlab personal token v9mPZiQbchS2sqMSwdRu
# Uncomment the line if you want fastlane to automatically update itself


# increment_build_number(xcodeproj: XCODE_PROJECT)

# increment_version_number(
# bump_type: "patch",
#  xcodeproj: XCODE_PROJECT,
#)

#settings_to_override = {
# :BUNDLE_IDENTIFIER => MY_APP_ID,
#  :PROVISIONING_PROFILE_SPECIFIER => MY_PROFILE,
#  :DEVELOPMENT_TEAM => MY_TEAM,
#}
update_fastlane

default_platform(:ios)

platform :ios do
  desc "Upload .ipa to TestFlight"
  lane :build do
    
    build_app(
      
      gym(
      scheme: "mobilecicd",
      clean: true,
      output_directory: "build",
      export_options: {
        method: "development"
      }
    )
    )
  end
end
